ghostrider:
  admin:
    DCOS_OAUTH: "True"
    CPHALO_URL: "https://api-cpg.ng.cloudpassage.com"
    USER_FILE: "creds/users.yml"
    SEC_GRP_SUFFIX: "admin"
    LOCK_HQ_HTTPS: "True"
    # PORTS is space delimited list
    PORTS: "443"
  backend-user:
    DCOS_OAUTH: "False"
    CPHALO_URL: "https://api-cpg.ng.cloudpassage.com"
    USER_FILE: "creds/users.yml"
    SEC_GRP_SUFFIX: "backend-user"
    LOCK_HQ_HTTPS: "False"
    # PORTS is space delimited list
    PORTS: "1145"
    users:
      hq@cloudpassage.com: 64.124.161.130
      ldevlin+OPS@cloudpassage.com:
      ebeuerlein@cloudpassage.com:
      jlee+ops@cloudpassage.com:
      snicholson@cloudpassage.com:
      amandernack@cloudpassage.com:
      dromano@cloudpassage.com:
      Kent@cloudpassageOPS:
      dgindin@cloudpassage.com:

gitserver:
  INSTANCE_COUNT: 3
